# Generated by Django 4.2.2 on 2025-02-04 19:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите почту в формате, к примеру: user@mail.ru",
                        max_length=254,
                        unique=True,
                        verbose_name="Почта пользователя",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Укажите имя",
                        max_length=150,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Укажите фамилию",
                        max_length=150,
                        verbose_name="Фамилия пользователя",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату рождения",
                        null=True,
                        verbose_name="Дата рождения пользователя",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Укажите телефон",
                        max_length=30,
                        null=True,
                        verbose_name="Телефон пользователя",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/users/",
                        verbose_name="Аватар пользователя",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="token"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="MakeAnAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reception_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата записи на прием"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Имя пациента",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Фамилия пациента",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Укажите телефон",
                        max_length=30,
                        null=True,
                        verbose_name="Телефон пациента",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату рождения",
                        null=True,
                        verbose_name="Дата рождения пациента",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Адрес расположения клиники",
                    ),
                ),
                (
                    "my_doctor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.staffmedical",
                        verbose_name="Врач по направлению диагностики",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
            },
        ),
    ]
