# Generated by Django 4.2.2 on 2025-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя сотрудника",
                        max_length=150,
                        verbose_name="Имя специалиста",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        help_text="Введите отчество сотрудника",
                        max_length=150,
                        verbose_name="Отчество специалиста",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию сотрудника",
                        max_length=150,
                        verbose_name="Фамилия специалиста",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Введите должость сотрудника",
                        max_length=150,
                        verbose_name="Должность специалиста",
                    ),
                ),
                (
                    "about_employee",
                    models.TextField(
                        blank=True,
                        help_text="Укажите специализацию и навыки",
                        null=True,
                        verbose_name="Информация о специалисте",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/staff/",
                        verbose_name="Аватар специалиста",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Стаж специалиста"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
