# Generated by Django 4.2.2 on 2025-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                (
                    "information",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание услуги"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Стоимость услуги")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/medical/",
                        verbose_name="Аватар специалиста",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинская услуга",
                "verbose_name_plural": "Медицинские услуги",
            },
        ),
    ]
