# Generated by Django 4.2.2 on 2025-02-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medical",
            name="subscription_to_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.makeanappointment",
                verbose_name="Запись на услугу",
            ),
        ),
    ]
